language: c
os: linux
dist: bionic
addons:
  apt:
    update: true
    packages:
    # Build tools
    - autoconf
    - automake
    - autopoint
    - build-essential
    - git
    - gtk-doc-tools
    - intltool
    - iso-codes
    - libtool
    - libxml2-utils
    - perl
    - xsltproc

    # Desktop app toolkit
    - libasound-dev
    - libatk1.0-dev
    - libcairo-dev
    - libfontconfig1-dev
    - libfreetype6-dev
    - libgdk-pixbuf2.0-dev
    - libglib2.0-dev
    - libgtk2.0-dev
    - libharfbuzz-dev
    - libjson-glib-dev
    - libpango1.0-dev
    - libwebkitgtk-dev
    - libxcursor-dev
    - libxext-dev
    - libxmu-dev
    - libxt-dev
    - shared-mime-info

    # Image libraries
    - libaa1-dev
    - libgexiv2-dev
    - libgs-dev
    - libheif-dev
    - libjpeg-dev
    - libmng-dev
    - libopenexr-dev
    - libopenjp2-7-dev
    - libpng-dev
    - libpoppler-glib-dev
    - libraw-dev
    - librsvg2-dev
    - libtiff-dev
    - libwebp-dev
    - libwmf-dev
    - libxpm-dev

    # Compression libraries
    - libbz2-dev
    - liblzma-dev
    - zlib1g-dev

    # Misc libraries
    - libjson-c-dev
    - libspiro-dev
    - libsuitesparse-dev
    - libumfpack5
    - libnss3-dev

    # Python support
    - python-cairo-dev
    - python-dev
    - python-gtk2-dev

    # For the tests
    - appstream-util
    - desktop-file-utils

    # Meson
    - python3
    - python3-pip
    - python3-setuptools
    - python3-wheel
    - ninja-build

    # Upstream recommended packages
    - libtool 
    - gjs
    - gtk-3-examples
    - jasper
    - libappstream-glib-dev
    - libarchive-dev
    - libavcodec-dev
    - libavformat-dev
    - libavutil-dev
    - libgs-dev
    - libgtk-3-dev
    - gobject-introspection
    - libgudev-1.0-dev
    - liblcms2-dev
    - liblensfun-dev
    - librsvg2-bin
    - libsdl2-dev
    - libswscale-dev
    - libv4l-dev
    - libwebkit2gtk-4.0-dev
    - luajit
    - python-gi-dev
    - python3-venv
    - ruby
    - w3m
    - asciidoc
    - libgirepository1.0-dev

env:
  global:
    - INSTALL_PREFIX=/tmp/glimpse-prefix
  jobs:
    - SRC_PREFIX=$TRAVIS_BUILD_DIR
      PATH=$INSTALL_PREFIX/bin:$PATH
      PKG_CONFIG_PATH=$INSTALL_PREFIX/lib/pkgconfig:$INSTALL_PREFIX/lib/x86_64-linux-gnu/pkgconfig:$INSTALL_PREFIX/share/pkgconfig:$PKG_CONFIG_PATH
      LD_LIBRARY_PATH=$INSTALL_PREFIX/lib:$INSTALL_PREFIX/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
      ACLOCAL_FLAGS="-I $INSTALL_PREFIX/share/aclocal $ACLOCAL_FLAGS"
      arch="$(dpkg-architecture -qDEB_HOST_MULTIARCH 2> /dev/null)"
      XDG_DATA_DIRS=$INSTALL_PREFIX/share:/usr/local/share:/usr/share

before_install:
- mkdir -p $INSTALL_PREFIX/share/aclocal
- git submodule update --init
- git clone https://gitlab.gnome.org/GNOME/babl.git $SRC_PREFIX/babl
- git clone https://gitlab.gnome.org/GNOME/gegl.git $SRC_PREFIX/gegl
- pip3 install meson
before_script:
- cd $SRC_PREFIX/babl
- "meson builddir --prefix=$INSTALL_PREFIX --buildtype=release -Db_lto=true -Dwith-docs=false"
- cd $SRC_PREFIX/babl/builddir
- ninja && ninja install
- cd $SRC_PREFIX/mypaint-brushes
- ./autogen.sh
- "./configure --prefix=$INSTALL_PREFIX"
- make && make install
- cd $SRC_PREFIX/libmypaint
- ./autogen.sh
- "./configure --prefix=$INSTALL_PREFIX"
- make && make install
- cd $SRC_PREFIX/gegl
- "meson builddir --prefix=$INSTALL_PREFIX --buildtype=release -Db_lto=true -Ddocs=false"
- cd $SRC_PREFIX/gegl/builddir
- ninja && ninja install
script:
- cd $SRC_PREFIX
- "./autogen.sh --prefix=$INSTALL_PREFIX --disable-gtk-doc --without-xvfb-run"
- make && make install
- make check VERBOSE=1
