name: Glimpse Dev Sanity Check CI

# Triggers the workflow on push or pull request events, but only for the dev-g210 branch
on:
  push:
    branches: [ dev-g210 ]
  pull_request:
    branches: [ dev-g210 ]

jobs:
  build-linux:
    runs-on: ubuntu-20.04
          
    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Ubuntu 20.04 runner
      run: sudo apt-get --quiet update --yes
            
    - name: Install build dependencies
      run: sudo apt-get --quiet install --yes build-essential git python3 python3-pip python3-setuptools python3-wheel ninja-build libgirepository1.0-dev valac
      
    - name: Install meson
      run: yes | sudo pip3 install meson
      
    - name: Set global environment variables
      run: |
        echo ::set-env name=SRC_PREFIX::${{ github.workspace }}
        echo ::set-env name=INSTALL_PREFIX::$HOME/glimpse-prefix
        echo ::set-env name="$(dpkg-architecture -qDEB_HOST_MULTIARCH 2> /dev/null)"
        
    - name: Set build environment variables
      run: |
        echo ::set-env name=PKG_CONFIG_PATH::$INSTALL_PREFIX/lib/pkgconfig:$INSTALL_PREFIX/lib/x86_64-linux-gnu/pkgconfig:$INSTALL_PREFIX/share/pkgconfig:$PKG_CONFIG_PATH
        echo ::set-env name=LD_LIBRARY_PATH::$INSTALL_PREFIX/lib:$INSTALL_PREFIX/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
        echo ::set-env name=ACLOCAL_FLAGS::"-I $INSTALL_PREFIX/share/aclocal $ACLOCAL_FLAGS"
        echo ::set-env name=XDG_DATA_DIRS::$INSTALL_PREFIX/share:/usr/local/share:/usr/share
        echo ::set-env name=PATH::$HOME/.local/bin:$INSTALL_PREFIX/bin:$PATH
    
    - name: Clone BABL from GNOME gitlab server
      run: git clone https://gitlab.gnome.org/GNOME/babl.git $HOME/babl
      
    - name: Clone MyPaint-Brushes from Github
      run: git clone https://github.com/mypaint/mypaint-brushes.git $HOME/mypaint-brushes
      
    - name: Clone LibMyPaint from Github
      run: git clone https://github.com/mypaint/libmypaint.git $HOME/libmypaint
      
    - name: Clone GEGL from GNOME gitlab server
      run: git clone https://gitlab.gnome.org/GNOME/gegl.git $HOME/gegl
      
    - name: Create install prefix
      run: |
        mkdir -p $INSTALL_PREFIX/share/aclocal
      
    - name: Build BABL 0.1.74
      run: |
        cd $HOME/babl
        git checkout BABL_0_1_74
        meson builddir --prefix=$INSTALL_PREFIX --buildtype=release -Db_lto=true -Dwith-docs=false
        cd $HOME/babl/builddir
        ninja && ninja install
        
    - name: Build mypaint-brushes submodule
      run: |
        cd $HOME/mypaint-brushes
        git checkout v2.0.2
        ./autogen.sh
        ./configure --prefix=$INSTALL_PREFIX
        make && make install
    
    - name: Build libmypaint submodule
      run: |
        cd $HOME/libmypaint
        git checkout v1.5.1
        ./autogen.sh
        ./configure --prefix=$INSTALL_PREFIX
        make && make install
        
    - name: Build GEGL 0.4.22
      run: |
        cd $HOME/gegl
        git checkout GEGL_0_4_22
        meson builddir --prefix=$INSTALL_PREFIX --buildtype=release -Db_lto=true -Ddocs=false
        cd $HOME/gegl/builddir
        ninja && ninja install
        
    - name: Build in-development version of Glimpse Image Editor
      run: |
        cd $SRC_PREFIX
        ./autogen.sh --prefix=$INSTALL_PREFIX --disable-gtk-doc --without-xvfb-run --disable-python
        make && make install
    
    - uses: actions/upload-artifact@v1
      with:
        name: glimpse-dev-x86_64-linux-gnu
        path: $HOME/glimpse-prefix
